import { FC, PropsWithChildren } from "react";

import "@/styles/globals.css";

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <head>
      <title>Next.JS & Nest.JS Boilerplate by MDReal</title>
      <meta name="description" content="Generated by Vercel & Modified by MDReal" />
    </head>

    <body>{children}</body>
  </html>
);

export default RootLayout;
